spring:
  application:
    name: service-consumer

server:
  port: 9001

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3
    metadata-map:
      instance-id: "${spring.application.name}:${random.value}"
#      turbine-cluster: consumer-cluster
